# 1. Why numpy
- numpy는 pandas, scikit-learn, tesorflow등 데이터 사이언스 분야에서 사용되는 라이브러리들의 토대가 되는 라이브러리이다. 
- numpy 그 자체로는 높은 수준의 데이터 분석 기능을 제공하지 않지만 numpy를 활용해 데이터를 python 상에서 표현하고 다룰 줄 알아야만 데이터 분석이라는 그 이후 단계로 나아갈 수 있다.
- numpy를 사용하면 다차원 배열을 효율적으로 다룰 수 있다. 

In [2]:
import numpy as np

In [2]:
math_score = np.array([[11,12],[21,22]])
math_score

array([[11, 12],
       [21, 22]])

In [3]:
# broadcasting
math_score + 1

array([[12, 13],
       [22, 23]])

In [4]:
np.mean(math_score)

16.5

![nd_array vs list](src/ndarray_list.png)
- 크기가 100개 이내인 경우 numpy는 순수 파이썬 구현보다도 오히려 낮은 성능을 보이는 경향이 있다.
- 하지만 코어부분이 C로 구현되어 동일한 연산을 하더라도 python에 비하여 속도가 빠르다.
- 라이브러리에 구현되어있는 함수들을 활용해 짧고 간결한 코드 작성이 가능한다. 
- 효율적인 메모리 사용이 가능하도록 구현된다.

- list
    - 파이썬 리스트는 결국 포인터의 배열
    - 경우에 따라서 각각 객체가 메모리 여기저기 흩어져 있다.
    - 그러므로 캐시 활용이 어렵다.

- ndarray
    - ndarray는 타입을 명시하여 원소의 배열로 데이터를 유지
    - 다차원 데이터도 연속된 메모리 공간이 할당됨
        - type이 지정되었기 때문
    - 많은 연산이 dimensions과 strides를 잘 활용하면 효율적으로 가능
        - 가령  trasnpose는 strides를 바꾸는 것으로 거의 공짜
    - ndarray 수현 방식을 떠올리면 어떻게 성능을 낼 수 있는지 상상가능

In [7]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
x.strides

(8, 4)

- 중요한 부분은 다음과 같다.
    - data는 변하지 않고, data를 바라보는 stride와 dimension의 변화만 존재하기 때문에 속도가 빠른 것이다.

- np.average와 np.mean의 차이
    - np.mean은 산술평균
    - np.average의 가중평균
    - 현재 아래에서는 weight를 주지 않았기 때문에 똑같이 나오지 않았다.

In [11]:
np.mean(range(1,11))

5.5

In [12]:
np.average(range(1,11))

5.5

In [13]:
np.average(range(1,11), weights=range(10, 0, -1))

4.0

# 2. 다차원 배열 생성하기
- 동일한 사이즈의 변수를 저장해야되기 때문에, 데이터를 통일시켜야 한다.
    - 정수형의 defalut data type은 'int64'이다.
    - 부호없는 정수형의 defalut data type은 'unit64'이다. -> unsigned integer
    - 실수형의 defalt data type은 'float64'이다.

In [14]:
float_array = np.array([[1,2],[3,4]], dtype="float64")
float_array.dtype

dtype('float64')

- numpy내에서 구현되어있ㄴ믄 다차원 배열 생성방법
    - [docs](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html)

- empty보다는 zeors가 낫다. 
    - 0으로 초기화한다는 의미이기 때문이다.

In [15]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

- eye > identity

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

- np.full보다는 아래방식이 많이 쓰임

In [23]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [24]:
10*np.ones((2,3), dtype=int)

array([[10, 10, 10],
       [10, 10, 10]])

In [25]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [26]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

## 3.다차원 배열 다루기

In [4]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- min 값을 구한다.
    - 각 column에 대한 min 값을 구한다. --> 0
    - 각 row에 대한 min 값을 구한다. --> 1

In [5]:
np.amin(A, 0)

array([1, 2, 3])

In [6]:
np.amin(A, 1)

array([1, 4, 7])

- max 값을 구한다.
    - 각 column에 대한 max 값을 구한다. --> 0
    - 각 row에 대한 max 값을 구한다. --> 1

In [7]:
np.amax(A, 0)

array([7, 8, 9])

In [8]:
np.amax(A, 1)

array([3, 6, 9])

In [9]:
np.amax(A)

9

- np.ptp
    - range of values (max - min) along an axis
    - 각 column에 대한 max 값을 구한다. --> 0
    - 각 row에 대한 max 값을 구한다. --> 1


In [10]:
np.ptp(A, 0)

array([6, 6, 6])

In [11]:
np.ptp(A, 1)

array([2, 2, 2])

In [12]:
np.ptp(A)

8

- np.median
    - 중앙값 찾는 method
    - 각 column에 대한 max 값을 구한다. --> 0
    - 각 row에 대한 max 값을 구한다. --> 1


In [14]:
np.median(A, 0)

array([4., 5., 6.])

In [15]:
np.median(A, 1)

array([2., 5., 8.])

In [16]:
np.median(A)

5.0

- np.mean
    - 산술평균을 찾는 method
        - 가중 평균을 찾으려면 np.average를 사용해야 한다.
    - 각 column에 대한 max 값을 구한다. --> 0
    - 각 row에 대한 max 값을 구한다. --> 1


In [18]:
np.mean(A, 0)

array([4., 5., 6.])

In [19]:
np.mean(A, 1)

array([2., 5., 8.])

In [20]:
np.mean(A)

5.0

- np.std
    - 표준편차를 구한다.
    - 각 column에 대한 max 값을 구한다. --> 0
    - 각 row에 대한 max 값을 구한다. --> 1


In [21]:
np.std(A, 0)

array([2.44948974, 2.44948974, 2.44948974])

In [22]:
np.std(A, 1)

array([0.81649658, 0.81649658, 0.81649658])

In [24]:
np.std(A)

2.581988897471611

- slicing
    - `array[row start:row end, column start:column end]`
    - column부분은 생략 가능하다.

In [25]:
A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

- indexing
    - `array[0, 0]`
    - `array[0][0]`

In [26]:
A[[0,2],]

array([[1, 2, 3],
       [7, 8, 9]])

In [29]:
A[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

- indexing&slicing - 차원
    - 정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮은 차원의 배열이 생성되지만, 슬라이싱만 사용하면 원본 배열과 동일한 차원의 배열이 생성된다.

> only slicing

In [37]:
slicedrow = A[0:1, :]
print(slicedrow, slicedrow.shape, slicedrow.ndim)

[[1 2 3]] (1, 3) 2


> indexing and slicing

In [39]:
indexedrow = A[0, :]
print(indexedrow, indexedrow.shape, indexedrow.ndim)

[1 2 3] (3,) 1


- 값 복사 & 참조
    - 인덱싱은 값을 복사해온다.
        - 복사된 값을 변경해도 원본의 값은 변하지 않는다.

In [40]:
b = A[0,0]
b = 100
print(A[0,0])
print("------------------------------")
print(b)

1
------------------------------
100


- 값 복사 & 참조
    - 슬라이싱 된 배열은 원본 배열과 같은 데이터를 참조한다.
        - 슬라이싱된 배열을 수정하면 원본 배열 역시 수정된다.

In [43]:
c = A[0:2, 0:2]
c[0,0] = 100 
print(A)
print("------------------------------")
print(c)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
------------------------------
[[100   2]
 [  4   5]]


- boolean 배열 인덱싱
    - 불리언 배열 인덱싱을 통해 배열 속 요소를 취사 선택할 수 있다. 불리언 배열 인덱싱은 특정 조건을 만족하게 하는 요소만 선택하고자 할 때 자주 사용된다.

In [45]:
bool_idx = (A > 2)
bool_idx

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
print(A[bool_idx])
print(A[A>2])

[100   3   4   5   6   7   8   9]
[100   3   4   5   6   7   8   9]


- 정수 배열 인덱싱

In [49]:
A

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [48]:
print(A[[0,1,2],[0,1,2]])

[100   5   9]


In [50]:
print(np.array([A[0,0], A[1,1], A[2,2]]))

[100   5   9]


- 전치(transpose)

In [51]:
A.T

array([[100,   4,   7],
       [  2,   5,   8],
       [  3,   6,   9]])